### ISSUE TITLE
Pasting text longer than the visible window causes the text and rendering to become offset

### ISSUE THREAD

**Issue by qqii** [funmaker/bqneditor#1]
![image](https://github.com/funmaker/bqneditor/assets/6891353/c44ae51b-63a7-4ef3-b442-3a8c2b9796b2)

The longer you paste, the worst it is. I've seen something similar in [a project using EditorConfig](https://github.com/braver/programmingfonts/pull/128/files) where they were missing some calls to refresh the state.

**Comment by funmaker** [comment]
Should be fixed in v2.0.1

**Comment by qqii** [comment]
Yup, can confirm! Thanks - I'll give daily driving it a go.
